apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Pre-Prod Config (Testing Environment)
configMapGenerator:
- name: bankapp-config
  literals:
    - db_url="jdbc:mysql://RDS_PREPROD_ENDPOINT:3306/bankappdb"

# Release Candidate Tags
images:
- name: bankapp:placeholder
  newName: YOUR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/bankapp
  newTag: rc-latest
